---

include:
  - project: pipelines_focus_grp/devops_pipeline_accelerator
    ref: $DPA_BRANCH
    file: entrypoints/gitlab/cf-infrastructure.yml
    rules:
      - if: '$SOURCE_PROJECT == "pipelines_focus_grp/devops_pipeline_accelerator" && $CI_PIPELINE_SOURCE == "pipeline" && $TEST_PIPELINE == "true"'
  
  - project: pipelines_focus_grp/devops_pipeline_accelerator
    ref: feature/cf-pipeline-structure
    file: entrypoints/gitlab/cf-infrastructure.yml
    rules:
      - if: $TEST_PIPELINE != "true"
