---
variables:
  AWS_REGION: us-east-2
  DEV_AWS_ACCOUNT: 316172404479
  DEV_ARN_ROLE: arn:aws:iam::316172404479:role/dpa-gitlab-access-role
  DEV_DEPLOY: "false"
  DEV_ENV: "dev"
  INT_AWS_ACCOUNT: 448599500132
  INT_ARN_ROLE: arn:aws:iam::448599500132:role/dpa-gitlab-access-role
  INT_DEPLOY: "true"
  INT_ENV: "dev"
  AWS_CREDS_TARGET_ROLE: arn:aws:iam::448599500132:role/dpa-gitlab-access-role
  TERRAFORM_TEST_CHECKOV: "false"
  TERRAFORM_TEST_TERRASCAN: "true"

include:
  - project: pipelines_focus_grp/devops_pipeline_accelerator
    ref: $DPA_BRANCH
    file: entrypoints/gitlab/cf-infrastructure.yml
    rules:
      - if: '$SOURCE_PROJECT == "pipelines_focus_grp/devops_pipeline_accelerator" && $CI_PIPELINE_SOURCE == "pipeline" && $TEST_PIPELINE == "true"'
  
  - project: pipelines_focus_grp/devops_pipeline_accelerator
    ref: feature/terrafom-deployments
    file: entrypoints/gitlab/cf-infrastructure.yml
    rules:
      - if: $TEST_PIPELINE != "true"