Parameters:
  BucketName:
    Description: s3 bucket name
    Type: String
    Default: "pipeline-accelerator-1"

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Sub "${BucketName}-${AWS::StackName}"
