---

'Terraform Entrypoint Test app':
  trigger:
    project: pipelines_focus_grp/pipeline-tools/test-entrypoints/infra-terraform-app
    branch: feature/terraform-deploy-jobs
    strategy: depend
  variables:
    SOURCE_PROJECT: $CI_PROJECT_PATH
    TEST_PIPELINE: "true"
    DPA_BRANCH: $CI_COMMIT_BRANCH
    DEV_DEPLOY: "true"

'CloudFormation Entrypoint Test app':
  trigger:
    project: pipelines_focus_grp/pipeline-tools/test-entrypoints/infra-cloudformation-app
    branch: main
    strategy: depend
  variables:
    SOURCE_PROJECT: $CI_PROJECT_PATH
    TEST_PIPELINE: "true"
    DPA_BRANCH: $CI_COMMIT_BRANCH
    DEV_DEPLOY: "true"