--- 
include:
  - local: stages/deploy/terraform/terraform-deployer.yml


'INT Terraform Plan':
  stage: INT Pre-Deploy
  resource_group: int
  extends: .terraform-plan
  variables:
    AWS_ACCOUNT: $INT_AWS_ACCOUNT
    ENVIRONMENT: $INT_ENV
    JOB: $APP_JOB
    PROJECT: $APP_PROJECT
    ROLE_ARN: $INT_ARN_ROLE
    TF_ROOT: $APP_TF_ROOT
    TEST_PIPELINE: $TEST_PIPELINE
  dependencies:
    - 'Download deployment artifact'
  needs:
    - 'Download deployment artifact'
  rules:
    - if: !reference [ .generic, branch-with-mr ]
      when: on_success
    - if: !reference [.int-terraform-deploy, tag]
      when: never
    - if: !reference [.int-terraform-deploy, mr]
      when: on_success
    - if: !reference [.int-terraform-deploy, branch-without-mr]
      when: on_success
    - if: !reference [.int-terraform-deploy, main]
      when: on_success

'INT Terraform apply':
  stage: INT Deploy
  resource_group: int
  extends: .terraform-apply
  variables:
    AWS_ACCOUNT: $INT_AWS_ACCOUNT
    ENVIRONMENT: $INT_ENV
    JOB: $APP_JOB
    PROJECT: $APP_PROJECT
    ROLE_ARN: $INT_ARN_ROLE
    TF_ROOT: $APP_TF_ROOT
    TEST_PIPELINE: $TEST_PIPELINE
  dependencies:
    - 'INT Terraform Plan'
    - 'Download deployment artifact'
  rules:
    - if: !reference [ .generic, branch-with-mr ]
      when: never
    - if: !reference [.int-terraform-deploy, tag]
      when: never
    - if: !reference [.int-terraform-deploy, mr]
      when: never
    - if: !reference [.int-terraform-deploy, branch-without-mr]
      when: never
    - if: !reference [.int-terraform-deploy, main]
      when: on_success