Parameters:
  BucketName2:
    Description: s3 bucket name
    Type: String
    Default: "pipeline-accelerator-2"

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Sub "${BucketName2}"
